# Generated by Django 4.1.6 on 2023-06-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_goods_product_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='colour',
            new_name='color',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
